Repository pharo-spec/NewTools, pull requests merged in 2024-04, with the labels that each got.

#731 Add 3 new entries to easily access the new tools from the System menu.
  src/NewTools-FileBrowser/StFileBrowserAbstractPresenter.class.st
  src/NewTools-Finder/StFinderPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsApplication.class.st
Labels: enhancement

#734 Fix Preview Settings Browser: does not open when a custom setting is used
  src/NewTools-SettingsBrowser/StSettingsApplication.class.st
Labels: bug

#736 Fix issue while trying to display file setting items
  src/NewTools-Playground/StPlaygroundPresenter.class.st
  src/NewTools-SettingsBrowser/AbstractFileReference.extension.st
  src/NewTools-SettingsBrowser/StLabeledMultiLineDirectorySelectionPresenter.class.st
  src/NewTools-SettingsBrowser/StLabeledMultiLineFileSelectionPresenter.class.st
  src/NewTools-SettingsBrowser/StLabeledMultiLinePresenter.class.st
  src/NewTools-SettingsBrowser/StSettingBooleanPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingDirectoryPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingDropListPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingFilePresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingMultipleDropListPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingNumberPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingSHStyleButtonPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingTextPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingsApplication.class.st
  src/NewTools-SettingsBrowser/StSettingsMainPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsPagePresenter.class.st
Labels: bug, enhancement

#733 Removing old object-centric breakpoint's integration to the inspector
  src/NewTools-DebugPointsBrowser/DebugPointBrowserPresenter.class.st
  src/NewTools-ObjectCentricBreakpoints/StBreakpointCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StHaltOnCallCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StHaltOnReadCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StHaltOnStateAccessCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StHaltOnWriteCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StHaltOnceOnCallCommand.class.st
  src/NewTools-ObjectCentricBreakpoints/StMetaBrowserPresenter.extension.st
  src/NewTools-ObjectCentricBreakpoints/StObjectInspectorPresenter.extension.st
  src/NewTools-ObjectCentricBreakpoints/StRawInspectionPresenter.extension.st
Labels: debugger

#726 Fix code highlighting in debug points browser, for debug points set on AST node
  src/NewTools-DebugPointsBrowser/DebugPointCodePresenter.class.st
  src/NewTools-DebugPointsBrowser/DebugPointNodeTarget.extension.st
Labels: bug, debugger
