Repository pharo-spec/NewTools, pull requests merged in 2024-07, with the labels that each got.

#793 Update transmissionBlock: -> transmits:
  src/NewTools-Inspector/StInspectorTransmissionNode.class.st
Labels: enhancement

#794 Add critics on class option
  src/NewTools-CodeCritiques/StClassCritiqueBrowserPresenter.class.st
  src/NewTools-CodeCritiques/StCritiqueClassRuleSelectorPresenter.class.st
  src/NewTools-CodeCritiques/SycCmClassCritiqueCommand.class.st
Labels: enhancement

#785 [P12][Backport] adding test to ensure it is possible to recompile code within a bloc with a dead home context twice
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
Labels: debugger, Backport!

#811 Use equality to compare file references in file navigation system
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
Labels: bug

#807 Adding command to add breakpoints in the debugger
  src/NewTools-Debugger-Commands/StBreakOnStackCommand.class.st
  src/NewTools-Debugger/StDebugger.class.st
  src/NewTools-Debugger/StDebuggerActionModel.class.st
Labels: enhancement, debugger
