Repository pharo-spec/NewTools, pull requests merged in 2024-06, with the labels that each got.

#766 Update after selection in Color Picker
  src/NewTools-SettingsBrowser/Color.extension.st
  src/NewTools-SettingsBrowser/SettingDeclaration.extension.st
  src/NewTools-SettingsBrowser/StSettingSHStyleButtonColorPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingSectionPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsChanged.class.st
Labels: bug

#723 adding test to ensure it is possible to recompile code within a bloc with a dead home context twice
  src/NewTools-Debugger-Tests/StDebuggerActionModelTest.class.st
Labels: bug, debugger, Backport!

#772 Make setting pages less dense without comments for each setting
  src/NewTools-SettingsBrowser/StLabeledMultiLinePresenter.class.st
  src/NewTools-SettingsBrowser/StLabeledSettingDirectorySelectionPresenter.class.st
  src/NewTools-SettingsBrowser/StLabeledSettingFileSelectionPresenter.class.st
  src/NewTools-SettingsBrowser/StLabeledSettingPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingDirectoryPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingFilePresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingNodePresenter.class.st
  src/NewTools-SettingsBrowser/StSettingPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingTextPresenterItem.class.st
  src/NewTools-SettingsBrowser/StSettingsAbstractPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsApplication.class.st
  src/NewTools-SettingsBrowser/StSettingsCategoriesPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsCategoryItemPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsMainPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsPagePresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsToolbarPresenter.class.st
Labels: enhancement, need more work

#758 Remove deprecated classes and methods
  src/NewTools-FileBrowser/StMorphicUIManager.class.st
  src/NewTools-Inspector-Extensions/Array2D.extension.st
  src/NewTools-Inspector-Extensions/Class.extension.st
  src/NewTools-Inspector/StInspection.class.st
  src/NewTools-Inspector/StInspector.class.st
  src/NewTools-Inspector/StInspectorPresenter.class.st
  src/NewTools-Inspector/StInspectorTransmissionNode.class.st
  src/NewTools-Inspector/StMetaBrowser.class.st
  src/NewTools-Inspector/StPresenterInspection.class.st
  src/NewTools-Inspector/StRawInspection.class.st
  src/NewTools-MethodBrowsers/AbstractMessageCentricBrowser.class.st
  src/NewTools-MethodBrowsers/MessageBrowser.class.st
  src/NewTools-MethodBrowsers/MessageBrowserPresenter.class.st
  src/NewTools-MethodBrowsers/MessageList.class.st
  src/NewTools-MethodBrowsers/StMessageBrowser.class.st
  src/NewTools-MethodBrowsers/StMessageBrowserPresenter.class.st
  src/NewTools-MethodBrowsers/VersionBrowser.class.st
  src/NewTools-MethodBrowsers/VersionBrowserPresenter.class.st
  src/NewTools-SystemReporter/StReporter.class.st
  src/NewTools-SystemReporter/StSizeReporter.class.st
  src/NewTools-SystemReporter/StSystemReporter.class.st
Labels: need more work

#784 [P12][Backport] fix `#needRequestorScope` of StDebuggerContextInteractionModel so that its bindings can be used when evaluating code in the debugger
  src/NewTools-Debugger/StDebuggerContextInteractionModel.class.st
Labels: debugger, Backport!

#788 File Browser: Add "disable preview"
  src/NewTools-FileBrowser/StFileBrowserSettings.class.st
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
  src/NewTools-FileBrowser/StFileSystemPresenter.class.st
Labels: enhancement

#790 Enable multiple selection in the open files/directories dialog
  src/NewTools-FileBrowser/StFileDialogPresenter.class.st
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
  src/NewTools-FileBrowser/StOpenFileOrDirectoryPresenter.class.st
  src/NewTools-FileBrowser/StOpenFilePresenter.class.st
Labels: enhancement

#770 Categorise rewriter rules by pragma to allow easy extension
  src/NewTools-RewriterTools-Backend/StRewriterDemoRules.class.st
Labels: need more work

#792 File Browser: Enable multiple file selection for opening files or directories
  src/NewTools-FileBrowser-Tests/StBreadcrumbPresenterTest.class.st
  src/NewTools-FileBrowser-Tests/StOpenFilePresenterTest.class.st
  src/NewTools-FileBrowser/StFileDialogPresenter.class.st
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
  src/NewTools-FileBrowser/StFileSystemPresenter.class.st
  src/NewTools-FileBrowser/StOpenFileOrDirectoryPresenter.class.st
  src/NewTools-FileBrowser/StOpenFilePresenter.class.st
Labels: enhancement
