Repository pharo-spec/NewTools, pull requests merged in 2024-09, with the labels that each got.

#829 Speedup class search and minor fixes
  src/NewTools-Finder-Tests/StFinderClassTest.class.st
  src/NewTools-Finder/StFinderClassSearch.class.st
  src/NewTools-Finder/StFinderPragmaSearch.class.st
  src/NewTools-Finder/StFinderSelectorSearch.class.st
  src/NewTools-Finder/StFinderSettings.class.st
  src/NewTools-Finder/StMethodFinder.class.st
Labels: bug, enhancement

#822 Fix missing updates in File Browser file/directory name presenter
  src/NewTools-FileBrowser-Tests/StOpenDirectoryPresenterTest.class.st
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
  src/NewTools-FileBrowser/StPathBreadcrumbPresenter.class.st
Labels: bug

#831 Fix Autoscroll file tree presenter when opened
  src/NewTools-FileBrowser/StDirectoryTreePresenter.class.st
  src/NewTools-FileBrowser/StFileDialogPresenter.class.st
  src/NewTools-FileBrowser/StFileNavigationSystemPresenter.class.st
  src/NewTools-FileBrowser/StFileSystemPresenter.class.st
  src/NewTools-FileBrowser/StNoteBookPreviewerPresenter.class.st
Labels: bug

#834 Add setting browser tabs
  src/NewTools-SettingsBrowser/StSettingPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsCategoryItemPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsPageNotebookPresenter.class.st
  src/NewTools-SettingsBrowser/StSettingsPagePresenter.class.st
Labels: enhancement

#838 New finder enhacements
  src/NewTools-Finder/StFinderExampleSearch.class.st
  src/NewTools-Finder/StFinderModel.class.st
  src/NewTools-Finder/StFinderPresenter.class.st
  src/NewTools-Finder/StFinderResult.class.st
  src/NewTools-Finder/StFinderSearch.class.st
  src/NewTools-Finder/StFinderSearchBar.class.st
  src/NewTools-Finder/StFinderSearchOptions.class.st
  src/NewTools-Finder/StFinderSettings.class.st
Labels: enhancement

#839 Use new message browser instead of morphic-based system navigation
  src/NewTools-MethodBrowsers/StMessageListPresenter.class.st
Labels: enhancement

#842 16566 fix vocabulary in debugger commands
  src/NewTools-Sindarin-Commands-Tests/SindarinCommandsTest.class.st
  src/NewTools-Sindarin-Commands/SindarinJumpToCaretCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinSkipAllToSelectionCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinSkipThroughSelectionCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinSkipUpToCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInClassCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextCallInObjectCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextExecutionCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextExecutionInClassCommand.class.st
  src/NewTools-Sindarin-Commands/SindarinStepToNextExecutionInObjectCommand.class.st
Labels: debugger

#841 Message Browser advances (scoping)
  src/NewTools-MethodBrowsers/RBBrowserEnvironment.extension.st
  src/NewTools-MethodBrowsers/RBClassEnvironment.extension.st
  src/NewTools-MethodBrowsers/RBClassHierarchyEnvironment.extension.st
  src/NewTools-MethodBrowsers/RBCompositeEnvironment.extension.st
  src/NewTools-MethodBrowsers/RBPackageEnvironment.extension.st
  src/NewTools-MethodBrowsers/StAbstractMessageCentricBrowserPresenter.class.st
  src/NewTools-MethodBrowsers/StMessageBrowser.class.st
  src/NewTools-MethodBrowsers/StMessageListPresenter.class.st
  src/NewTools-MethodBrowsers/StMessageToolbarPresenter.class.st
Labels: enhancement

#846 SycCmClassCritiqueCommand should be in Extras submenu
  src/NewTools-CodeCritiques/StCritiqueBrowserPresenter.class.st
  src/NewTools-CodeCritiques/SycCmClassCritiqueCommand.class.st
Labels: enhancement

#845 Update the Browser search presenter with search modes.
  src/NewTools-Core/StBrowserSearchPresenter.class.st
Labels: enhancement
